feat: routes for appointment services
medicomas/documed-backend-express pull request #25
Opened 2023-11-11 20:25 UTC by damarizz

closes #14

2023-11-12 04:34 UTC, paoloose requested changes

2023-11-12 04:34 UTC, paoloose commented on src/router/patient.ts
> +    );
Esta ruta recibe al usuario (doctor) que realizó la petición en `req.body.id_user`, cosa que no es necesario, porque la id del usuario se encuentra en los claims del token (línea 37; el token se firma con la id del usuario logueado)

https://github.com/medicomas/documed-backend-express/blob/e7eae97467721d9989f356cb64334d2676f30084/src/router/auth.ts#L35-L47

Todas las rutas que involucren acciones que realiza un doctor (usuario) deberían utilizar el middleware de `authWithUserMiddleware`

2023-11-12 04:34 UTC, paoloose commented on src/router/patient.ts
> +    );
Debería usar `authWithUserMiddleware`, así sabes de qué doctor vino la petición (`req.user`) y puedes verificar si le pertenece o no la cita

2023-11-12 04:34 UTC, paoloose commented on src/services/appointment.services.ts
> +        });
`startAppointment` debería recibir también la id del doctor que está iniciándolo, de esta forma al `where` puedes agregarle la constraint de que la cita debe pertenecerle al doctor (`Appointment.id_doctor`)

2023-11-12 04:34 UTC, paoloose commented on src/router/patient.ts
> +router.get(":id/consultas/", async (req, res) => {
Pasé un buen rato viendo por qué no corría, reinicié insomnia, debugueé el server, pero era que necesitaba el forward slash al inicio `/` XD

2023-11-14 05:39 UTC, damarizz commented
changes done! waiting patiently for feedback 🥳 btw i couldn't test any of my routes due to a swagger error 😿

2023-11-15 04:13 UTC, paoloose approved these changes
![](https://i.fluffy.cc/BPgxZkmsrgmfcDFDCNWC3m4CW0gCJF7w.gif)

2023-11-15 04:14 UTC, paoloose commented
![](https://i.fluffy.cc/BPgxZkmsrgmfcDFDCNWC3m4CW0gCJF7w.gif)

2023-11-15 04:20 UTC, merged